package biliapi

const (
	endpointNav     = "https://api.bilibili.com/x/web-interface/nav"
	endpointNavStat = "https://api.bilibili.com/x/web-interface/nav/stat"

	endpointNow        = "https://api.bilibili.com/x/click-interface/click/now"
	endpointReportNow  = "https://api.bilibili.com/x/report/click/now"
	endpointBuvid      = "https://api.bilibili.com/x/frontend/finger/spi"
	endpointGetBuvid   = "https://api.bilibili.com/x/web-frontend/getbuvid"
	endpointShortLink  = "https://api.bilibili.com/x/share/click"
	endpointMathJax    = "https://api.bilibili.com/x/web-frontend/mathjax/tex"
	endpointRTCTime    = "https://api.live.bilibili.com/xlive/open-interface/v1/rtc/getTimestamp"
	endpointServerDate = "https://interface.bilibili.com/serverdate.js"

	endpointClientZone       = "https://api.bilibili.com/x/web-interface/zone"
	endpointClientLiveIPInfo = "https://api.live.bilibili.com/xlive/web-room/v1/index/getIpInfo"
	endpointClientIPInfo     = "https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr"
	endpointClientAppIP      = "https://app.bilibili.com/x/resource/ip"

	endpointUserSpaceInfo    = "https://api.bilibili.com/x/space/wbi/acc/info"
	endpointUserCard         = "https://api.bilibili.com/x/web-interface/card"
	endpointUserMyInfo       = "https://api.bilibili.com/x/space/myinfo"
	endpointUserCards        = "https://api.bilibili.com/x/polymer/pc-electron/v1/user/cards"
	endpointUserArcSearch    = "https://api.bilibili.com/x/space/wbi/arc/search"
	endpointUserUpStat       = "https://api.bilibili.com/x/space/upstat"
	endpointUserRelationStat = "https://api.bilibili.com/x/relation/stat"
	endpointUserNavNum       = "https://api.bilibili.com/x/space/navnum"
	endpointUserNotice       = "https://api.bilibili.com/x/space/notice"
	endpointUserNoticeSet    = "https://api.bilibili.com/x/space/notice/set"
	endpointUserTags         = "https://api.bilibili.com/x/space/acc/tags"
	endpointUserTagsSet      = "https://api.bilibili.com/x/space/acc/tags/set"
	endpointUserTopArcSet    = "https://api.bilibili.com/x/space/top/arc/set"
	endpointUserTopArcCancel = "https://api.bilibili.com/x/space/top/arc/cancel"
	endpointUserMasterpiece  = "https://api.bilibili.com/x/space/masterpiece"
	endpointUserMasterAdd    = "https://api.bilibili.com/x/space/masterpiece/add"
	endpointUserMasterCancel = "https://api.bilibili.com/x/space/masterpiece/cancel"

	endpointVideoView       = "https://api.bilibili.com/x/web-interface/wbi/view"
	endpointVideoViewDetail = "https://api.bilibili.com/x/web-interface/wbi/view/detail"
	endpointVideoDesc       = "https://api.bilibili.com/x/web-interface/archive/desc"
	endpointVideoPageList   = "https://api.bilibili.com/x/player/pagelist"
	endpointVideoPlayURL    = "https://api.bilibili.com/x/player/wbi/playurl"
	endpointVideoPlayerV2   = "https://api.bilibili.com/x/player/wbi/v2"
	endpointVideoStat       = "https://api.bilibili.com/x/web-interface/archive/stat"
	endpointVideoRelated    = "https://api.bilibili.com/x/web-interface/archive/related"
	endpointVideoOnline     = "https://api.bilibili.com/x/player/online/total"
	endpointVideoShot       = "https://api.bilibili.com/x/player/videoshot"
	endpointVideoAIGet      = "https://api.bilibili.com/x/web-interface/view/conclusion/get"
	endpointVideoLike       = "https://api.bilibili.com/x/web-interface/archive/like"
	endpointVideoHasLike    = "https://api.bilibili.com/x/web-interface/archive/has/like"
	endpointVideoCoins      = "https://api.bilibili.com/x/web-interface/archive/coins"
	endpointVideoFavoured   = "https://api.bilibili.com/x/v2/fav/video/favoured"
	endpointVideoCoin       = "https://api.bilibili.com/x/web-interface/coin/add"
	endpointVideoFav        = "https://api.bilibili.com/x/v3/fav/resource/deal"
	endpointVideoTriple     = "https://api.bilibili.com/x/web-interface/archive/like/triple"
	endpointVideoHistory    = "https://api.bilibili.com/x/v2/history/report"
	endpointVideoHeartbeat  = "https://api.bilibili.com/x/click-interface/web/heartbeat"

	endpointSearchDefault = "https://api.bilibili.com/x/web-interface/wbi/search/default"
	endpointSearchSquare  = "https://api.bilibili.com/x/web-interface/wbi/search/square"
	endpointSearchHotword = "https://s.search.bilibili.com/main/hotword"
	endpointSearchSuggest = "https://s.search.bilibili.com/main/suggest"
	endpointSearchAll     = "https://api.bilibili.com/x/web-interface/wbi/search/all/v2"
	endpointSearchType    = "https://api.bilibili.com/x/web-interface/wbi/search/type"

	endpointCommentList   = "https://api.bilibili.com/x/v2/reply"
	endpointCommentMain   = "https://api.bilibili.com/x/v2/reply/wbi/main"
	endpointCommentReply  = "https://api.bilibili.com/x/v2/reply/reply"
	endpointCommentDialog = "https://api.bilibili.com/x/v2/reply/dialog/cursor"
	endpointCommentHot    = "https://api.bilibili.com/x/v2/reply/hot"
	endpointCommentInfo   = "https://api.bilibili.com/x/v2/reply/info"
	endpointCommentCount  = "https://api.bilibili.com/x/v2/reply/count"
	endpointCommentAdd    = "https://api.bilibili.com/x/v2/reply/add"
	endpointCommentAction = "https://api.bilibili.com/x/v2/reply/action"
	endpointCommentHate   = "https://api.bilibili.com/x/v2/reply/hate"
	endpointCommentDel    = "https://api.bilibili.com/x/v2/reply/del"
	endpointCommentTop    = "https://api.bilibili.com/x/v2/reply/top"
	endpointCommentReport = "https://api.bilibili.com/x/v2/reply/report"

	endpointDanmakuXMLList    = "https://api.bilibili.com/x/v1/dm/list.so"
	endpointDanmakuWebSeg     = "https://api.bilibili.com/x/v2/dm/wbi/web/seg.so"
	endpointDanmakuWebView    = "https://api.bilibili.com/x/v2/dm/web/view"
	endpointDanmakuHistoryIdx = "https://api.bilibili.com/x/v2/dm/history/index"
	endpointDanmakuHistorySeg = "https://api.bilibili.com/x/v2/dm/web/history/seg.so"
	endpointDanmakuHistoryXML = "https://api.bilibili.com/x/v2/dm/history"
	endpointDanmakuSnapshot   = "https://api.bilibili.com/x/v2/dm/ajax"
	endpointDanmakuThumbStats = "https://api.bilibili.com/x/v2/dm/thumbup/stats"
	endpointDanmakuPost       = "https://api.bilibili.com/x/v2/dm/post"
	endpointDanmakuRecall     = "https://api.bilibili.com/x/dm/recall"
	endpointDanmakuThumbAdd   = "https://api.bilibili.com/x/v2/dm/thumbup/add"
	endpointDanmakuReport     = "https://api.bilibili.com/x/dm/report/add"

	endpointFavFolderInfo       = "https://api.bilibili.com/x/v3/fav/folder/info"
	endpointFavCreatedListAll   = "https://api.bilibili.com/x/v3/fav/folder/created/list-all"
	endpointFavCollectedList    = "https://api.bilibili.com/x/v3/fav/folder/collected/list"
	endpointFavResourceList     = "https://api.bilibili.com/x/v3/fav/resource/list"
	endpointFavResourceIDs      = "https://api.bilibili.com/x/v3/fav/resource/ids"
	endpointFavResourceInfos    = "https://api.bilibili.com/x/v3/fav/resource/infos"
	endpointFavFolderAdd        = "https://api.bilibili.com/x/v3/fav/folder/add"
	endpointFavFolderEdit       = "https://api.bilibili.com/x/v3/fav/folder/edit"
	endpointFavFolderDel        = "https://api.bilibili.com/x/v3/fav/folder/del"
	endpointFavResourceCopy     = "https://api.bilibili.com/x/v3/fav/resource/copy"
	endpointFavResourceMove     = "https://api.bilibili.com/x/v3/fav/resource/move"
	endpointFavResourceBatchDel = "https://api.bilibili.com/x/v3/fav/resource/batch-del"
	endpointFavResourceClean    = "https://api.bilibili.com/x/v3/fav/resource/clean"

	endpointHistoryCursor      = "https://api.bilibili.com/x/web-interface/history/cursor"
	endpointHistoryLegacy      = "https://api.bilibili.com/x/v2/history"
	endpointHistoryDelete      = "https://api.bilibili.com/x/v2/history/delete"
	endpointHistoryClear       = "https://api.bilibili.com/x/v2/history/clear"
	endpointHistoryShadow      = "https://api.bilibili.com/x/v2/history/shadow"
	endpointHistoryShadowSet   = "https://api.bilibili.com/x/v2/history/shadow/set"
	endpointHistoryToView      = "https://api.bilibili.com/x/v2/history/toview"
	endpointHistoryToViewAdd   = "https://api.bilibili.com/x/v2/history/toview/add"
	endpointHistoryToViewDel   = "https://api.bilibili.com/x/v2/history/toview/del"
	endpointHistoryToViewClear = "https://api.bilibili.com/x/v2/history/toview/clear"
)
